steps:
  # Deploy to Cloud Run in production
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'cloud-hello-prod', '--image', 'gcr.io/belajargcp-396102/cloud-hello:$SHORT_SHA', 
           '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']